import type { CandidateProfile } from '../resume/profile.ts';
import type { NormalisedJob } from '../jobs/types.ts';
import type { MatchResult } from '../match/score.ts';
import { AiClient, hashKey } from './client.ts';
import { CoverLetter, MatchSummary, TailoredResume } from './schemas.ts';
import {
  COVER_LETTER_SYSTEM,
  MATCH_SUMMARY_SYSTEM,
  RESUME_TAILOR_SYSTEM,
  coverLetterPrompt,
  matchSummaryPrompt,
  profileContext,
  resumeTailorPrompt,
  type Tone,
} from './prompts.ts';
import { verifyClaims, verifyProvenance, type Violation } from './verify.ts';
import { buildMirrorPlan } from '../resume/mirror.ts';
import { PROFILE_DRAFT_SYSTEM, ProfileDraft, profileDraftPrompt } from '../resume/draft.ts';

/**
 * The AI services, one per pipeline stage (spec §18).
 *
 * Each is small and independent so it can be improved without touching the
 * others, and each returns its verification result alongside its output. The
 * caller decides what to do with a violation; nothing here silently ships text
 * that failed a check.
 *
 * Cache keys are content-addressed on everything that changes the answer: the
 * job's text, the profile version, and (for letters) the tone. Two job boards
 * carrying the same posting therefore cost one call, not two.
 */

export interface Verified<T> {
  output: T;
  violations: Violation[];
  /** False when a blocking violation was found. The caller must not ship it. */
  safe: boolean;
}

/**
 * The canonical keys the matcher accepted as transferable for this job. Passed
 * to the verifier so it does not block the AI for reporting them.
 */
function transferableKeys(match: MatchResult): string[] {
  return match.requirements.required
    .filter((v) => v.weight > 0 && v.weight < 1)
    .map((v) => v.requirement);
}

function jobFingerprint(job: NormalisedJob): string {
  // Title and company matter because the same description under a different
  // title is a different job; description length guards against a truncated
  // copy colliding with a complete one.
  return hashKey(job.title, job.company, String(job.description.length), job.description.slice(0, 3000));
}

export class AiServices {
  private readonly ai: AiClient;
  private readonly profile: CandidateProfile;

  constructor(ai: AiClient, profile: CandidateProfile) {
    this.ai = ai;
    this.profile = profile;
  }

  private get stableContext(): string {
    return profileContext(this.profile);
  }

  /** Plain-English explanation of an already-computed match. */
  async explainMatch(job: NormalisedJob, match: MatchResult): Promise<Verified<MatchSummary>> {
    const output = await this.ai.complete({
      kind: 'match-summary',
      // The score is part of the key: if the matcher changes its mind, the
      // explanation must be regenerated rather than served stale.
      cacheKey: hashKey(jobFingerprint(job), this.profile.version, match.overall, match.recommendation),
      system: MATCH_SUMMARY_SYSTEM,
      stableContext: this.stableContext,
      prompt: matchSummaryPrompt(job, match),
      schema: MatchSummary,
      maxTokens: 2048,
      effort: 'low',
    });

    const check = verifyClaims(
      this.profile,
      [output.verdict, ...output.strengths, ...output.concerns, ...output.preparation],
      { transferable: transferableKeys(match) }
    );
    return { output, violations: check.violations, safe: check.ok };
  }

  async tailorResume(job: NormalisedJob, match: MatchResult): Promise<Verified<TailoredResume>> {
    // Which of the posting's words this candidate has earned the right to use.
    // Computed here rather than in the route so every caller -- the API, the
    // batch script, a test -- gets the same decisions.
    const mirror = buildMirrorPlan(match.requirements.required, match.requirements.preferred, this.profile);

    const output = await this.ai.complete({
      kind: 'resume-tailor',
      // 'mirror-v2' invalidates every entry cached before vocabulary mirroring
      // existed. Those were generated by a prompt that discarded the employer's
      // wording, so serving one now would silently undo the fix.
      cacheKey: hashKey('mirror-v2', jobFingerprint(job), this.profile.version),
      system: RESUME_TAILOR_SYSTEM,
      stableContext: this.stableContext,
      prompt: resumeTailorPrompt(job, match, mirror),
      schema: TailoredResume,
      // 16000. Both 5000 and 8192 truncated the JSON mid-object.
      //
      // The output is genuinely large -- reordered bullets for every role plus a
      // provenance entry per rewrite -- and adaptive thinking tokens count
      // against this same budget, which is the part that caught me out.
      //
      // Measured cost of this stage is $0.157 per job on Sonnet 5 -- by far the
      // most expensive stage, and the reason it is generated on demand rather
      // than for every job that clears the score threshold.
      maxTokens: 16000,
      effort: 'high',
    });

    const texts = [output.summary, ...output.bullets.flatMap((b) => b.bullets)];
    const check = verifyClaims(this.profile, texts, { transferable: transferableKeys(match) });
    const provenanceViolations = verifyProvenance(this.profile, output.provenance);

    // A skill order that names something not in the profile is an addition
    // dressed up as a reordering, so it is checked separately.
    const known = new Set(this.profile.skills.map((s) => s.name.toLowerCase()));
    const invented = output.skillOrder.filter((name) => !known.has(name.toLowerCase()));
    const skillViolations: Violation[] = invented.map((name) => ({
      severity: 'blocking' as const,
      kind: 'unevidenced_skill' as const,
      detail: `"${name}" was placed in the skills list but is not a skill in the profile.`,
      offendingText: name,
    }));

    // A relabel is only a relabel if the thing being relabelled exists. A pair
    // naming a skill the profile does not have is an addition wearing a
    // disguise, and it is the one new way this stage could lie.
    const labelViolations: Violation[] = output.skillLabels
      .filter((pair) => !known.has(pair.profileSkill.toLowerCase()))
      .map((pair) => ({
        severity: 'blocking' as const,
        kind: 'unevidenced_skill' as const,
        detail:
          `The output asks to print "${pair.printAs}" as the label for "${pair.profileSkill}", ` +
          'but no such skill exists in the profile.',
        offendingText: pair.printAs,
      }));

    // The prompt lists the forbidden terms; this checks the model obeyed. The
    // prompt is the request, this is the guarantee -- the same division of
    // labour verify.ts is built on.
    const forbidden = [...mirror.confirm, ...mirror.gaps].flatMap((entry) => entry.surface);
    const haystack = [
      output.targetTitle,
      output.summary,
      ...output.skillOrder,
      ...output.skillLabels.map((p) => p.printAs),
      ...output.bullets.flatMap((b) => b.bullets),
    ]
      .join('\n')
      .toLowerCase();
    const leaked = forbidden.filter((term) => {
      const escaped = term.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      return new RegExp(`(^|[^a-z0-9+#])${escaped}($|[^a-z0-9+#])`, 'i').test(haystack);
    });
    const leakViolations: Violation[] = [...new Set(leaked)].map((term) => ({
      severity: 'blocking' as const,
      kind: 'unevidenced_skill' as const,
      detail:
        `"${term}" is a requirement of this posting that the candidate has not confirmed, ` +
        'and it appears in the tailored resume. Confirm it on the job page if it is true, ' +
        'or regenerate.',
      offendingText: term,
    }));

    const violations = [
      ...check.violations,
      ...provenanceViolations,
      ...skillViolations,
      ...labelViolations,
      ...leakViolations,
    ];
    return { output, violations, safe: violations.every((v) => v.severity !== 'blocking') };
  }

  /**
   * Read a CV into a draft profile for the person to check.
   *
   * The odd one out in this class, and deliberately so. Every other service here
   * generates text FROM a profile and is verified against it; this one has no
   * profile to verify against, because producing the first one is the job.
   *
   * So the safeguard is different in kind: nothing this returns is saved. It is
   * a `ProfileDraft`, a type nothing else in the application accepts, and it can
   * only become a profile by passing through a review screen where a person
   * confirms each field. The model does the typing; the human remains the source
   * of truth, which is the same rule the JSON upload enforced — only now the
   * user is not the one doing the typing.
   *
   * `stableContext` is empty here for the same reason: the profile is the
   * output, not the input, so there is nothing stable to cache across calls.
   */
  async draftProfileFromCv(cvText: string): Promise<ProfileDraft> {
    return this.ai.complete({
      kind: 'profile-draft',
      // Keyed on the document itself, so re-uploading the same CV after a failed
      // review costs nothing.
      cacheKey: hashKey('profile-draft-v1', cvText),
      system: PROFILE_DRAFT_SYSTEM,
      stableContext: '',
      prompt: profileDraftPrompt(cvText),
      schema: ProfileDraft,
      // A full CV with an evidence line and a source quote per skill is a large
      // structured output; 8192 truncated a 40-skill draft mid-array.
      maxTokens: 16000,
      effort: 'medium',
    });
  }

  async writeCoverLetter(job: NormalisedJob, match: MatchResult, tone: Tone): Promise<Verified<CoverLetter>> {
    const output = await this.ai.complete({
      kind: `cover-letter`,
      cacheKey: hashKey(jobFingerprint(job), this.profile.version, tone),
      system: COVER_LETTER_SYSTEM,
      stableContext: this.stableContext,
      prompt: coverLetterPrompt(job, match, tone),
      schema: CoverLetter,
      maxTokens: 4096,
      effort: 'medium',
    });

    const check = verifyClaims(this.profile, [...output.paragraphs, ...output.claimsMade, output.subjectLine], {
      transferable: transferableKeys(match),
    });
    return { output, violations: check.violations, safe: check.ok };
  }
}

/**
 * Which jobs are worth spending a model call on.
 *
 * Below the threshold the deterministic score is already enough to say "no", and
 * paying to have that explained in prose is waste. Out-of-scope postings are
 * excluded outright: there is nothing useful to say about a nursing vacancy.
 */
export function shouldAnalyse(match: MatchResult, minScore = Number(process.env.AI_MIN_SCORE ?? 70)): boolean {
  return !match.relevance.outOfScope && match.overall >= minScore;
}
